### ISSUE TITLE
/roll command

### ISSUE THREAD

**Issue by MauritsArissen** [MauritsArissen/FakkaBot#4]
**Is your feature request related to a problem? Please describe.**
_This feature is not related to any current active problems_

**Describe the solution you'd like**
A command that allows users to do `/roll` which has the following requirements:

1. By default rolls a number from 1 to 6
2. Has an option to choose a specific type of dice, think of d4, d6 (default), d8, d10, d12, d16 & d20
3. Allow the player to choose his own range, so 0 - X where X is what the user defines

**Describe alternatives you've considered**
Make use of the command builder in discord.js, if not come up with another good solution

**Additional context**
For questions regarding this request contact Mau#1000 on discord or reply to this issue.

**Comment by Joestine** [comment]
Added /roll Command
